theme: "hugo-PaperMod"
baseURL: /
hasCJKLanguage: true
title: Monster
paginate: 5

googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

permalinks:
  post: /:year/:month/:day/:slug/

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Posts
                  url: post
                  weight: 1
                - name: Archive
                  url: archives
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Search
                  url: search/
                  weight: 15

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    title: Monster
    description: "A blog for Dr. Bin Xu to record something."
    keywords: [Blog, Note, Learning]
    author: Bin Xu
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        # favicon16x16:  "/favicon-16x16.png"
        # favicon32x32:  "/favicon-32x32.png"
        # apple_touch_icon:  "/apple-touch-icon.png"
        # safari_pinned_tab: "<link / abs url>"
    
    homeInfoParams:
        Title: "Hi there!"
        Content: >
            Welcome to blog for Dr. Bin Xu. It is uesd to record somthing.
    socialIcons:
        # - name: github
        #   url: "https://github.com/adityatelange/hugo-PaperMod"
        # - name: KoFi
        #   url: "https://ko-fi.com/adityatelange"
        - name: RsS
          url: "index.xml"
taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
