---
title: R code and functions for data analysis
author: Bin Xu
date: '2021-07-28'
slug: r-code-and-functions-for-data-analysis
categories:
  - 统计
tags: ["R", "数据分析"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

## 生存分析

```{r}
# 生存数据示例
library(survival)
library(survminer)

OS <- Surv(time = df$OS, event = df$OS_status)
RFS <- Surv(time = df$RFS, event = df$RFS_status)
```

### 画生存曲线

```{r}
library(survival)

ggsurvplot(fit = survfit(OS ~ 1, data = df), 
           palette = "jco", # or palette = c("#E7B800", "#2E9FDF"),
           
           # Allowed values are one of c("top", "bottom", "left", "right", "none"). 
           # Legend position can be also specified using a numeric vector c(x, y). 
           # In this case it is possible to position the legend inside the plotting area. 
           # x and y are the coordinates of the legend box. Their values should be between 0 and 1.
           legend = "none", 
           legend.title = "group",
           legend.labs = c("DCP responder", "DCP nonresponder"),
           
           pval = T, # 也可以直接指定要显示的p value
           # numeric vector, of length 2, specifying the x and y coordinates of the p-value. 
           # Default values are NULL.
           pval.coord = c(50, 1), 
           
           conf.int = F,
           
           surv.median.line = "hv",
           
           # title = "Progress-Free Survival",
           ylab = "Overall Survival",
           xlab = "Months",
           
           # axes.offset = F, # Default is TRUE. If FALSE, set the plot axes to start at the origin.
           ylim = c(0,1),
           break.y.by = 0.2,
           # surv.scale = "percent", 
           xlim = c(0, 60),
           break.x.by = 12,
           # xscale = "d_m", # will transform labels from days to months
           
           risk.table = T,
           risk.table.title = "Number at Risk",
           risk.table.y.text = F,
           risk.table.y.text.col = T,
           risk.table.height = 0.15,
           ggtheme = theme_survminer(base_size = 6),
           tables.theme = theme_cleantable(base_size = 6))
```


### 批量单因素logrank函数

```{r}
uni_logrank <- function(gvar, surv, df) {
  temp <- survdiff(as.formula(paste0(surv, " ~ ", gvar)), 
                   data = df)
  p.value <- round(broom::glance(temp)$p.value, 3)
  return(p.value)
}

# OS
uni_logrank_batch_OS <- sapply(vars, uni_logrank, "OS", df)
uni_logrank_batch_OS[uni_logrank_batch_OS < 0.05]

# RFS
uni_logrank_batch_RFS <- sapply(vars, uni_logrank, "RFS", df)
uni_logrank_batch_RFS[uni_logrank_batch_RFS < 0.05]
```

